[package]
name = "socket-server-mocker"
description = "Mock socket server in Rust, for testing various network clients."
authors = ["Thomas Prévost"]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/thomasarmel/socket-server-mocker"
categories = ["network-programming", "testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dev-dependencies]
reqwest = {version="0.11.12", features=["blocking"]}
postgres = "0.19.4"